// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Check if we have valid Supabase configuration
const hasSupabase = SUPABASE_URL && 
  SUPABASE_PUBLISHABLE_KEY && 
  SUPABASE_URL.startsWith('http') &&
  SUPABASE_URL.includes('supabase') &&
  SUPABASE_PUBLISHABLE_KEY.length > 20;

// Create a mock Supabase client for when Supabase is not configured
const createMockClient = (): SupabaseClient<Database> => {
  const mockClient = {
    auth: {
      getSession: async () => ({ 
        data: { session: null }, 
        error: null 
      }),
      signOut: async () => ({ error: null }),
      signInWithPassword: async () => ({ 
        data: { session: null, user: null }, 
        error: { message: 'Supabase not configured. Running in demo mode.' } 
      }),
      signUp: async () => ({ 
        data: { session: null, user: null }, 
        error: { message: 'Supabase not configured. Running in demo mode.' } 
      }),
      onAuthStateChange: () => ({ 
        data: { subscription: { unsubscribe: () => {} } }, 
        error: null 
      }),
      updateUser: async () => ({ 
        data: { user: null }, 
        error: { message: 'Supabase not configured' } 
      }),
    },
    from: (table: string) => ({
      select: (columns?: string) => ({
        eq: (column: string, value: any) => ({
          single: async () => ({ 
            data: null, 
            error: { message: 'Supabase not configured. Running in demo mode.' } 
          }),
          maybeSingle: async () => ({ 
            data: null, 
            error: null 
          }),
          limit: () => ({
            data: [],
            error: null
          }),
          order: () => ({
            data: [],
            error: null
          }),
          data: [],
          error: null
        }),
        limit: () => ({
          data: [],
          error: null
        }),
        order: () => ({
          data: [],
          error: null
        }),
        data: [],
        error: null
      }),
      insert: async (values: any) => ({ 
        data: null, 
        error: { message: 'Supabase not configured. Running in demo mode.' } 
      }),
      update: (values: any) => ({
        eq: async (column: string, value: any) => ({ 
          data: null, 
          error: { message: 'Supabase not configured. Running in demo mode.' } 
        }),
      }),
      upsert: async (values: any) => ({ 
        data: null, 
        error: { message: 'Supabase not configured. Running in demo mode.' } 
      }),
      delete: () => ({
        eq: async (column: string, value: any) => ({ 
          data: null, 
          error: { message: 'Supabase not configured. Running in demo mode.' } 
        }),
      }),
    }),
  } as any as SupabaseClient<Database>;

  return mockClient;
};

// Create the actual Supabase client or mock client
let supabaseInstance: SupabaseClient<Database>;

if (hasSupabase) {
  try {
    supabaseInstance = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        }
      }
    );
    console.log('✅ Supabase connected successfully');
  } catch (error) {
    console.warn('⚠️ Failed to initialize Supabase, using mock client:', error);
    supabaseInstance = createMockClient();
  }
} else {
  console.warn('⚠️ Supabase not configured. Running in demo mode.');
  console.warn('💡 To enable full features, add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Vercel environment variables.');
  supabaseInstance = createMockClient();
}

export const supabase = supabaseInstance;

// Export a helper to check if Supabase is configured
export const isSupabaseConfigured = hasSupabase;
